---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: server-install-centos-7
          suite: server-install-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-install-debian-9
          suite: server-install-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-install-ubuntu-1604
          suite: server-install-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-install-ubuntu-1804
          suite: server-install-ubuntu-1804
          requires: *lint_and_unit
      - final:
          requires:
            - server-install-centos-7
            - server-install-debian-9
            - server-install-ubuntu-1604
            - server-install-ubuntu-1804
