---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      # Server Installs
      - kitchen/dokken-single:
          name: server-install-centos-7
          suite: server-install-centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: server-install-debian-9
          suite: server-install-debian-9
          requires: [server-install-centos-7]
      - kitchen/dokken-single:
          name: server-install-ubuntu-1604
          suite: server-install-ubuntu-1604
          requires: [server-install-debian-9]
      - kitchen/dokken-single:
          name: server-install-ubuntu-1804
          suite: server-install-ubuntu-1804
          requires: [server-install-ubuntu-1604]
